### ISSUE TITLE
Extra samples in analysis reports

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_multiqc#22]
When samples in a run are processed in multiple batches all of the samples on the whole run appear in the summary table, rather than just those samples in the batch

e.g. https://platform.dnanexus.com/projects/G194zXj4b0ZfB9v1JBZbf6gg/data/?id.values=file-G1968B04kQ9VFqF6KvJpxpq7
12 samples were processed, but additional samples appear in the table.

**Comment by sophie22** [comment]
It is because MultiQC looks for the Stats.json file in the whole of the project and since demultiplexing was done for all samples on a chip/run, they are all included in the Stats.json (bcl2fastq module) and do show up in the Gen Stats table but only with the bcl2fastq data.
One workaround is to turn off the bcl2fastq columns when viewing reports, or I can set the bcl2fastq columns to not show up in Gen Stats. Another option is that I can take out the bcl2fastq section all together, but can't just include lane stats for a subset of samples.
